I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 154, in script
    call screen test_movie
renpy.display.screen.ScreenNotFound: Screen 'test_movie' is not known.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 154, in script
    call screen test_movie
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 695, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/statementexports.py", line 334, in call_screen
    renpy.exports.show_screen(_screen_name, *args, _transient=True, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 1355, in show_screen
    raise ScreenNotFound(name[0])
renpy.display.screen.ScreenNotFound: Screen 'test_movie' is not known.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.4.1.25072401
strahdica 1.0
Sun Sep 14 07:34:57 2025
